version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-bot-contpaqi
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CONTPAQI_API_URL=${CONTPAQI_API_URL}
      - CONTPAQI_API_KEY=${CONTPAQI_API_KEY}
      - NODE_ENV=production
    volumes:
      - ./logs:/app/logs
    networks:
      - bot-network
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  bot-network:
    driver: bridge

volumes:
  logs:
    driver: local